
DROP TABLE prestamos;
DROP TABLE usuarios;
DROP TABLE ejemplares;
DROP TABLE editoriales;
DROP TABLE autorias;
DROP TABLE autores;
DROP TABLE libros;
DROP TABLE areas_conocimiento;


-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-06 18:46:58 ECT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE areas_conocimiento (
    codarea      VARCHAR2(15) NOT NULL,
    nombrearea   VARCHAR2(250) NOT NULL,
    codareapadre VARCHAR2(15)
);

ALTER TABLE areas_conocimiento ADD CONSTRAINT areas_conocimiento_pk PRIMARY KEY ( codarea );

CREATE TABLE autores (
    idautor     INTEGER NOT NULL,
    nombreautor VARCHAR2(100) NOT NULL,
    pais        CHAR(2) NOT NULL,
    foto        BLOB,
    bio         VARCHAR2(2500),
    numlibros   INTEGER NOT NULL
);

ALTER TABLE autores ADD CONSTRAINT autores_pk PRIMARY KEY ( idautor );

-- AUTORES NUMLIBROS NO PUEDER SER NEGATIVO.
ALTER TABLE autores ADD CONSTRAINT numlibros_ck CHECK (numlibros > 0);

CREATE TABLE autorias (
    idlibro INTEGER NOT NULL,
    idautor INTEGER NOT NULL,
    orden   SMALLINT NOT NULL
);

ALTER TABLE autorias ADD CONSTRAINT autorias_pk PRIMARY KEY ( idlibro,
                                                              idautor );

-- En la tabla autorias, un mismo libro no puede tener dos o más autores con el mismo orden.
ALTER TABLE autorias ADD CONSTRAINT orden_unico UNIQUE (idlibro, orden);


CREATE TABLE editoriales (
    idedit     INTEGER NOT NULL,
    nombreedit VARCHAR2(100) NOT NULL,
    pais       VARCHAR2(100) NOT NULL,
    web        VARCHAR2(200)
);

ALTER TABLE editoriales ADD CONSTRAINT editoriales_pk PRIMARY KEY ( idedit );

CREATE TABLE ejemplares (
    idejemplar INTEGER NOT NULL,
    idlibro    INTEGER NOT NULL,
    ubicacion  VARCHAR2(40),
    status     CHAR(1) NOT NULL
);

ALTER TABLE ejemplares ADD CONSTRAINT ejemplares_pk PRIMARY KEY ( idejemplar );

-- EJEMPLARES ESTATUS TRES POSIBLES VALORES "D" DISPONIBLE, "P" PRESTADO, "B" DADO DE BAJA
ALTER TABLE ejemplares ADD CONSTRAINT status_ck CHECK (status in('D', 'P', 'B'));


CREATE TABLE libros (
    idlibro    INTEGER NOT NULL,
    isbm       VARCHAR2(15) NOT NULL,
    titulo     VARCHAR2(500) NOT NULL,
    sinopsis   VARCHAR2(2500),
    numpaginas INTEGER NOT NULL,
    idioma     CHAR(2),
    codarea    VARCHAR2(15) NOT NULL,
    anio       NUMBER(4) NOT NULL,
    nroedicion NUMBER(4) NOT NULL,
    idedit     INTEGER NOT NULL,
    imgpotada  BLOB
);

ALTER TABLE libros ADD CONSTRAINT libros_pk PRIMARY KEY ( idlibro );

ALTER TABLE libros ADD CONSTRAINT "libros __UN" UNIQUE ( isbm );

-- libros numpagina Debe ser mayor a 50 y menor a 2000.
ALTER TABLE libros ADD CONSTRAINT numPagina_ck CHECK (numpaginas > 50 AND numpaginas < 2000);

-- libros nroedicion Debe ser mayor a 0.
ALTER TABLE libros ADD CONSTRAINT nroedicion_ck CHECK (nroedicion > 0);

-- libros anio Debe ser mayor a 1800.
ALTER TABLE libros ADD CONSTRAINT anio_ck CHECK (anio > 1800);


CREATE TABLE prestamos (
    idprestamo       INTEGER NOT NULL,
    idejemplar       INTEGER NOT NULL,
    cedula           VARCHAR2(15) NOT NULL,
    fechaprestamo    DATE NOT NULL,
    fechavencimiento DATE NOT NULL,
    fechadevolucion  DATE,
    observacion      VARCHAR2(2000)
);

ALTER TABLE prestamos ADD CONSTRAINT prestamos_pk PRIMARY KEY ( idprestamo );

-- prestamos fechaDevolucion No debe ser inferior a la fecha de prestamo.
ALTER TABLE prestamos ADD CONSTRAINT fechadevolucion_ck CHECK (fechadevolucion > fechaprestamo);


CREATE TABLE usuarios (
    cedula    VARCHAR2(15) NOT NULL,
    apellidos VARCHAR2(50) NOT NULL,
    nombres   VARCHAR2(50) NOT NULL,
    direccion VARCHAR2(250),
    telefono1 VARCHAR2(20),
    telefono2 VARCHAR2(20),
    telefono3 VARCHAR2(20),
    email     VARCHAR2(60)
);

ALTER TABLE usuarios ADD CONSTRAINT usuarios_pk PRIMARY KEY ( cedula );

ALTER TABLE usuarios ADD CONSTRAINT usuarios__un UNIQUE ( email );

-- usuarios email Debe nescesariamente incluir el caracter especial "@" y debe
-- incluir al menos dos caracteres antes y despues del arroba.
ALTER TABLE usuarios ADD CONSTRAINT email_ck CHECK(email LIKE('__@__'));




ALTER TABLE areas_conocimiento
    ADD CONSTRAINT areas_conocimiento FOREIGN KEY ( codareapadre )
        REFERENCES areas_conocimiento ( codarea );

ALTER TABLE autorias
    ADD CONSTRAINT autorias_autores_fk FOREIGN KEY ( idautor )
        REFERENCES autores ( idautor );

ALTER TABLE autorias
    ADD CONSTRAINT "autorias_libros _FK" FOREIGN KEY ( idlibro )
        REFERENCES libros ( idlibro );

ALTER TABLE ejemplares
    ADD CONSTRAINT "ejemplares_libros _FK" FOREIGN KEY ( idlibro )
        REFERENCES libros ( idlibro );

ALTER TABLE libros
    ADD CONSTRAINT "libros _areas_conocimiento_FK" FOREIGN KEY ( codarea )
        REFERENCES areas_conocimiento ( codarea );

ALTER TABLE libros
    ADD CONSTRAINT "libros _editoriales_FK" FOREIGN KEY ( idedit )
        REFERENCES editoriales ( idedit );

ALTER TABLE prestamos
    ADD CONSTRAINT prestamos_ejemplares_fk FOREIGN KEY ( idejemplar )
        REFERENCES ejemplares ( idejemplar );

ALTER TABLE prestamos
    ADD CONSTRAINT prestamos_usuarios_fk FOREIGN KEY ( cedula )
        REFERENCES usuarios ( cedula );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0

SELECT tablespace_name, file_name
FROM dba_data_files
WHERE tablespace_name = 'TABLESPACE1'
AND owner = 'BIB_SARAGURO_OLIVER';

SELECT tablespace_name, file_name
FROM user_data_files
WHERE tablespace_name = 'TABLESPACE1';


