INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (1, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'BISTURÍES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (2, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'BOTELLA ROTA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (3, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'CUCHILLOS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (4, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'DAGA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (5, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'DESTORNILLADORES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (6, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'ESPADAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (7, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'ESTILETE');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (8, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'HACHAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (9, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'HOJAS DE AFEITAR');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (10, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'LANZA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (11, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'MACHETES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (12, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'NAVAJAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (13, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'NINGUNA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (14, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'OTROS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (15, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'OTROS ARMAS CORTAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (16, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'PICA HIELO');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (17, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'PUÑALES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (18, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'SE DESCONOCE');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (19, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'SIN DATO');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (20, 'ARMAS BLANCAS (OBJETO CORTANTE O PUNZANTE)', 'TIJERAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (21, 'ARMAS DE FUEGO', 'AMETRALLADORA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (22, 'ARMAS DE FUEGO', 'ARTESANAL');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (23, 'ARMAS DE FUEGO', 'CARABINA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (24, 'ARMAS DE FUEGO', 'CARTUCHERA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (25, 'ARMAS DE FUEGO', 'CARTUCHERAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (26, 'ARMAS DE FUEGO', 'FUSIL');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (27, 'ARMAS DE FUEGO', 'FUSILES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (28, 'ARMAS DE FUEGO', 'NINGUNA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (29, 'ARMAS DE FUEGO', 'OTROS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (30, 'ARMAS DE FUEGO', 'OTROS ARMAS CORTAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (31, 'ARMAS DE FUEGO', 'PISTOLA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (32, 'ARMAS DE FUEGO', 'PISTOLAS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (33, 'ARMAS DE FUEGO', 'REVÓLVER');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (34, 'ARMAS DE FUEGO', 'RIFLE');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (35, 'ARMAS DE FUEGO', 'RIFLES');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (36, 'ARMAS DE FUEGO', 'SE DESCONOCE');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (37, 'ARMAS DE FUEGO', 'SIN DATO');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (38, 'ARMAS DE FUEGO', 'SUBAMETRALLADORA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (39, 'NINGUNA', 'ARTESANAL');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (40, 'NINGUNA', 'NINGUNA');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (41, 'NINGUNA', 'OTROS');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (42, 'NINGUNA', 'SE DESCONOCE');
INSERT INTO utpl.arma (codigo, tipo, nombre) VALUES (43, 'SIN DATO', 'SIN DATO');
