INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (101, 'CUENCA', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (102, 'GIRON', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (103, 'GUALACEO', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (104, 'NABON', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (105, 'PAUTE', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (106, 'PUCARA', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (107, 'SAN FERNANDO', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (108, 'SANTA ISABEL', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (109, 'SIGSIG', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (110, 'OÑA', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (111, 'CHORDELEG', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (112, 'EL PAN', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (113, 'SEVILLA DE ORO', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (114, 'GUACHAPALA', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (115, 'CAMILO PONCE ENRIQUEZ', 1);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (201, 'GUARANDA', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (202, 'CHILLANES', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (203, 'CHIMBO', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (204, 'ECHEANDIA', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (205, 'SAN MIGUEL', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (206, 'CALUMA', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (207, 'LAS NAVES', 2);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (301, 'AZOGUES', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (302, 'BIBLIAN', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (303, 'CAÑAR', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (304, 'LA TRONCAL', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (305, 'EL TAMBO', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (306, 'DELEG', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (307, 'SUSCAL', 3);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (401, 'TULCAN', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (402, 'BOLIVAR', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (403, 'ESPEJO', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (404, 'MIRA', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (405, 'MONTUFAR', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (406, 'SAN PEDRO DE HUACA', 4);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (501, 'LATACUNGA', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (502, 'LA MANA', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (503, 'PANGUA', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (504, 'PUJILI', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (505, 'SALCEDO', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (506, 'SAQUISILI', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (507, 'SIGCHOS', 5);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (601, 'RIOBAMBA', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (602, 'ALAUSI', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (603, 'COLTA', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (604, 'CHAMBO', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (605, 'CHUNCHI', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (606, 'GUAMOTE', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (607, 'GUANO', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (608, 'PALLATANGA', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (609, 'PENIPE', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (610, 'CUMANDA', 6);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (701, 'MACHALA', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (702, 'ARENILLAS', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (703, 'ATAHUALPA', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (704, 'BALSAS', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (705, 'CHILLA', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (706, 'EL GUABO', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (707, 'HUAQUILLAS', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (708, 'MARCABELI', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (709, 'PASAJE', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (710, 'PIÑAS', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (711, 'PORTOVELO', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (712, 'SANTA ROSA', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (713, 'ZARUMA', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (714, 'LAS LAJAS', 7);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (801, 'ESMERALDAS', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (802, 'ELOY ALFARO', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (803, 'MUISNE', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (804, 'QUININDE', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (805, 'SAN LORENZO', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (806, 'ATACAMES', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (807, 'RIOVERDE', 8);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (808, 'LA CONCORDIA', 23);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (901, 'GUAYAQUIL', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (902, 'ALFREDO BAQUERIZO MORENO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (903, 'BALAO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (904, 'BALZAR', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (905, 'COLIMES', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (906, 'DAULE', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (907, 'DURAN', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (908, 'EMPALME', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (909, 'EL TRIUNFO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (910, 'MILAGRO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (911, 'NARANJAL', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (912, 'NARANJITO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (913, 'PALESTINA', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (914, 'PEDRO CARBO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (916, 'SAMBORONDON', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (918, 'SANTA LUCIA', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (919, 'SALITRE', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (920, 'SAN JACINTO DE YAGUACHI', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (921, 'PLAYAS', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (922, 'SIMON BOLIVAR', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (923, 'CRNEL. MARCELINO MARIDUEÑA', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (924, 'LOMAS DE SARGENTILLO', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (925, 'NOBOL', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (927, 'GNRAL. ANTONIO ELIZALDE', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (928, 'ISIDRO AYORA', 9);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1001, 'IBARRA', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1002, 'ANTONIO ANTE', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1003, 'COTACACHI', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1004, 'OTAVALO', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1005, 'PIMAMPIRO', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1006, 'SAN MIGUEL DE URCUQUI', 10);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1101, 'LOJA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1102, 'CALVAS', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1103, 'CATAMAYO', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1104, 'CELICA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1105, 'CHAGUARPAMBA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1106, 'ESPINDOLA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1107, 'GONZANAMA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1108, 'MACARA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1109, 'PALTAS', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1110, 'PUYANGO', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1111, 'SARAGURO', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1112, 'SOZORANGA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1113, 'ZAPOTILLO', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1114, 'PINDAL', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1115, 'QUILANGA', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1116, 'OLMEDO', 11);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1201, 'BABAHOYO', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1202, 'BABA', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1203, 'MONTALVO', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1204, 'PUEBLO VIEJO', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1205, 'QUEVEDO', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1206, 'URDANETA', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1207, 'VENTANAS', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1208, 'VINCES', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1209, 'PALENQUE', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1210, 'BUENA FE', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1211, 'VALENCIA', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1212, 'MOCACHE', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1213, 'QUINSALOMA', 12);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1301, 'PORTOVIEJO', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1302, 'BOLIVAR', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1303, 'CHONE', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1304, 'EL CARMEN', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1305, 'FLAVIO ALFARO', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1306, 'JIPIJAPA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1307, 'JUNIN', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1308, 'MANTA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1309, 'MONTECRISTI', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1310, 'PAJAN', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1311, 'PICHINCHA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1312, 'ROCAFUERTE', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1313, 'SANTA ANA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1314, 'SUCRE', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1315, 'TOSAGUA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1316, '24 DE MAYO', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1317, 'PEDERNALES', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1318, 'OLMEDO', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1319, 'PUERTO LOPEZ', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1320, 'JAMA', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1321, 'JARAMIJO', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1322, 'SAN VICENTE', 13);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1401, 'MORONA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1402, 'GUALAQUIZA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1403, 'LIMON INDANZA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1404, 'PALORA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1405, 'SANTIAGO', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1406, 'SUCUA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1407, 'HUAMBOYA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1408, 'SAN JUAN BOSCO', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1409, 'TAISHA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1410, 'LOGROÑO', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1411, 'PABLO SEXTO', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1412, 'TIWINTZA', 14);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1501, 'TENA', 15);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1503, 'ARCHIDONA', 15);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1504, 'EL CHACO', 15);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1507, 'QUIJOS', 15);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1509, 'CARLOS JULIO AROSEMENA TOLA', 15);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1601, 'PASTAZA', 16);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1602, 'MERA', 16);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1603, 'SANTA CLARA', 16);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1604, 'ARAJUNO', 16);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1701, 'QUITO', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1702, 'CAYAMBE', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1703, 'MEJIA', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1704, 'PEDRO MONCAYO', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1705, 'RUMIÑAHUI', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1707, 'SAN MIGUEL DE LOS BANCOS', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1708, 'PEDRO VICENTE MALDONADO', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1709, 'PUERTO QUITO', 17);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1801, 'AMBATO', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1802, 'BAÑOS DE AGUA SANTA', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1803, 'CEVALLOS', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1804, 'MOCHA', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1805, 'PATATE', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1806, 'QUERO', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1807, 'SAN PEDRO DE PELILEO', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1808, 'SANTIAGO DE PILLARO', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1809, 'TISALEO', 18);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1901, 'ZAMORA', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1902, 'CHINCHIPE', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1903, 'NANGARITZA', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1904, 'YACUAMBI', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1905, 'YANTZAZA', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1906, 'EL PANGUI', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1907, 'CENTINELA DEL CONDOR', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1908, 'PALANDA', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (1909, 'PAQUISHA', 19);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2001, 'SAN CRISTOBAL', 20);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2002, 'ISABELA', 20);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2003, 'SANTA CRUZ', 20);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2101, 'LAGO AGRIO', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2102, 'GONZALO PIZARRO', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2103, 'PUTUMAYO', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2104, 'SHUSHUFINDI', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2105, 'SUCUMBIOS', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2106, 'CASCALES', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2107, 'CUYABENO', 21);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2201, 'ORELLANA', 22);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2202, 'AGUARICO', 22);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2203, 'LA JOYA DE LOS SACHAS', 22);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2204, 'LORETO', 22);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2301, 'SANTO DOMINGO', 23);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2401, 'SANTA ELENA', 24);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2402, 'LA LIBERTAD', 24);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (2403, 'SALINAS', 24);
INSERT INTO utpl.canton (codigo, nombre, provincia_codigo) VALUES (9004, 'EL PIEDRERO', 3);
