INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D01', 'CUENCA NORTE', '10150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D02', 'CUENCA SUR', '10151');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D03', 'GIRON', '10250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D04', 'GUALACEO', '11150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D05', 'NABON', '10452');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D06', 'PAUTE', '10550');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D07', 'PONCE ENRIQUEZ', '11550');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('01D08', 'SIG SIG', '10950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('02D01', 'GUARANDA', '20150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('02D02', 'CHILLANES', '20250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('02D03', 'SAN MIGUEL', '20350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('02D04', 'SUBTROPICO', '20750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('03D01', 'AZOGUES', '30150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('03D02', 'CAÑAR', '30355');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('03D03', 'LA TRONCAL', '30450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('04D01', 'TULCAN', '40150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('04D02', 'MONTUFAR', '40253');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('04D03', 'ESPEJO', '40452');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D01', 'LATACUNGA', '50150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D02', 'LA MANA', '50251');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D03', 'PANGUA', '50351');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D04', 'DANSANTE', '50457');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D05', 'SIGCHOS', '50750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('05D06', 'SALCEDO', '50555');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('06D01', 'RIOBAMBA', '60150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('06D02', 'ALAUSI', '60550');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('06D03', 'PALLATANGA', '61050');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('06D04', 'COLTA', '60650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('06D05', 'GUANO', '60750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D01', 'PASAJE', '70950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D02', 'MACHALA', '70150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D03', 'ZARUMA', '71150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D04', 'PIÑAS', '70450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D05', 'HUAQUILLAS', '70250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('07D06', 'SANTA ROSA', '71250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D01', 'ESMERALDAS', '80163');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D02', 'ELOY ALFARO', '80258');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D03', 'ATACAMES', '80650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D04', 'QUININDE', '80450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D05', 'SAN LORENZO', '80554');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('08D06', 'RIO VERDE', '80750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D01', 'SUR', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D02', 'ESTEROS', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D03', '9 DE OCTUBRE', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D04', 'PORTETE', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D05', 'MODELO', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D06', 'FLORIDA', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D07', 'PASCUALES', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D08', 'NUEVA PROSPERINA', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D09', 'CEIBOS', '90150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D10', 'PROGRESO', '90156');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D11', 'JUJAN SIMON BOLIVAR', '90250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D12', 'NARANJAL BALAO', '91150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D13', 'BALZAR', '90450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D14', 'PEDRO CARBO', '92450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D15', 'EL EMPALME', '90850');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D16', 'EL TRIUNFO BUCAY', '90950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D17', 'MILAGRO', '91050');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D18', 'NARANJITO MARCELINO MARIDUEÑA', '91250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D19', 'DAULE', '90650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D20', 'SALITRE', '91950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D21', 'YAGUACHI', '92056');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D22', 'PLAYAS', '92150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D23', 'SAMBORONDON', '91651');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('09D24', 'DURAN', '90750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('10D01', 'CIUDAD BLANCA', '100150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('10D02', 'VALLE DEL AMANECER', '100450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('10D03', 'TIERRA DEL SOL', '100350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D01', 'LOJA', '110150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D02', 'CATAMAYO', '110350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D03', 'CATACOCHA', '110950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D04', 'SABANILLA', '111050');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D05', 'ESPINDOLA', '110651');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D06', 'CALVAS', '110250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D07', 'MACARA', '110851');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D08', 'SARAGURO', '111150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('11D09', 'ZAPOTILLO', '111352');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D01', 'BABAHOYO', '120150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D02', 'PUEBLOVIEJO', '120450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D03', 'QUEVEDO', '120550');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D04', 'VENTANAS', '121350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D05', 'VINCES', '120850');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('12D06', 'BUENA FE', '121050');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D01', 'PORTOVIEJO', '130150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D02', 'MANTA', '130850');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D03', 'JIPIJAPA', '130650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D04', '24 DE MAYO', '131650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D05', 'EL CARMEN', '130452');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D06', 'BOLIVAR JUNIN', '130250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D07', 'CHONE', '130350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D08', 'PICHINCHA', '131150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D09', 'PAJAN', '131052');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D10', 'PEDERNALES', '131750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D11', 'SUCRE', '132250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('13D12', 'ROCAFUERTE', '131250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D01', 'MORONA', '140150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D02', 'SANGAY', '140450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D03', 'CENTRO SUR', '140650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D04', 'SUR', '140253');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D05', 'TAISHA', '140950');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('14D06', 'MENDEZ', '140350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('15D01', 'TENA', '150150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('15D02', 'EL VALLE DE QUIJOS', '150450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('16D01', 'PASTAZA', '160150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('16D02', 'ARAJUNO', '160450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D01', 'NANEGAL', '170169');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D02', 'CALDERON', '170155');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D03', 'LA DELICIA', '170177');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D04', 'MANUELA SAENZ', '170150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D05', 'EUGENIO ESPEJO', '170150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D06', 'ELOY ALFARO', '170150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D07', 'QUITUMBE', '170150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D08', 'LOS CHILLOS', '170152');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D09', 'TUMBACO', '170183');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D10', 'CAYAMBE', '170251');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D11', 'RUMIÑAHUI - MEJIA', '170356');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('17D12', 'NOROCCIDENTE', '170750');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D01', 'AMBATO NORTE', '180150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D02', 'AMBATO SUR', '180150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D03', 'BAÑOS', '180250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D04', 'PATATE', '180757');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D05', 'PILLARO', '180854');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('18D06', 'QUERO', '180350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('19D01', 'ZAMORA', '190150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('19D02', 'PAQUISHA', '190351');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('19D03', 'CHINCHIPE', '190250');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('19D04', 'YANTZAZA', '190650');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('20D01', 'GALAPAGOS', '200350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('21D01', 'SUCUMBIOS', '210251');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('21D02', 'LAGO AGRIO', '210150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('21D03', 'PUTUMAYO', '210350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('21D04', 'SHUSHUFINDI', '210450');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('22D01', 'LA JOYA DE LOS SACHAS', '220350');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('22D02', 'ORELLANA LORETO', '220150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('22D03', 'AGUARICO', '220254');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('23D01', 'SANTO DOMINGO ESTE', '230150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('23D02', 'SANTO DOMINGO OESTE', '230150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('23D03', 'LA CONCORDIA', '80850');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('24D01', 'SANTA ELENA', '240150');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('24D02', 'LIBERTAD SALINAS', '240351');
INSERT INTO utpl.distrito (codigo, nombre, parroquia_codigo) VALUES ('90D01', 'EL PIEDRERO', '900451');
