INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (1, 'ÁREA PRIVADA', 'ESPACIO PRIVADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (2, 'ÁREA PRIVADA', 'TERRENO BALDÍO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (3, 'ÁREA PRIVADA', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (4, 'ÁREAS DE ACCESO PUBLICO', 'ALTAMAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (5, 'ÁREAS DE ACCESO PUBLICO', 'BOSQUES Y RESERVAS ECOLÓGICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (6, 'ÁREAS DE ACCESO PUBLICO', 'CANCHAS DE USO MÚLTIPLE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (7, 'ÁREAS DE ACCESO PUBLICO', 'CEMENTERIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (8, 'ÁREAS DE ACCESO PUBLICO', 'COLISEO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (9, 'ÁREAS DE ACCESO PUBLICO', 'ESTADIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (10, 'ÁREAS DE ACCESO PUBLICO', 'IGLESIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (11, 'ÁREAS DE ACCESO PUBLICO', 'LAGUNA-LAGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (12, 'ÁREAS DE ACCESO PUBLICO', 'MAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (13, 'ÁREAS DE ACCESO PUBLICO', 'MUELLE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (14, 'ÁREAS DE ACCESO PUBLICO', 'PARADA DE BUSES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (15, 'ÁREAS DE ACCESO PUBLICO', 'PARQUE Y PLAZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (16, 'ÁREAS DE ACCESO PUBLICO', 'PLAYA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (17, 'ÁREAS DE ACCESO PUBLICO', 'PLAZA DE TOROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (18, 'ÁREAS DE ACCESO PUBLICO', 'QUEBRADA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (19, 'ÁREAS DE ACCESO PUBLICO', 'RÍO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (20, 'ÁREAS DE ACCESO PUBLICO', 'SEMÁFORO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (21, 'ÁREAS DE ACCESO PUBLICO', 'TERRENO BALDÍO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (22, 'ÁREAS DE ACCESO PUBLICO', 'TROCHA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (23, 'ÁREAS DE ACCESO PUBLICO', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (24, 'ÁREAS DEDICADAS AL COMERCIO', 'ALMACEN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (25, 'ÁREAS DEDICADAS AL COMERCIO', 'BAZAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (26, 'ÁREAS DEDICADAS AL COMERCIO', 'CENTRO COMERCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (27, 'ÁREAS DEDICADAS AL COMERCIO', 'FERIA DE VEHÍCULO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (28, 'ÁREAS DEDICADAS AL COMERCIO', 'FERIA LIBRE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (29, 'ÁREAS DEDICADAS AL COMERCIO', 'FERRETERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (30, 'ÁREAS DEDICADAS AL COMERCIO', 'MERCADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (31, 'ÁREAS DEDICADAS AL COMERCIO', 'OTRO LOCAL COMERCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (32, 'ÁREAS DEDICADAS AL COMERCIO', 'PAPELERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (33, 'ÁREAS DEDICADAS AL COMERCIO', 'TIENDA-MICRO MERCADO-ABARROTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (34, 'ÁREAS DEDICADAS AL COMERCIO', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (35, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI FEMENINO-QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (36, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI MASCULINO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (37, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (38, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI MASCULINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (39, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI MASCULINO-LOJA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (40, 'CENTRO DE ADOLESCENTES INFRACTORES (CAI)', 'CAI MASCULINO-QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (41, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', '"\\"CPPL MASCULINO-CC GUAYAQUIL \\"\\"APREMIO\\"\\"\\""');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (42, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-BAHIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (43, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-EL INCA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (44, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (45, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-GUARANDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (46, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-MACAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (47, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MASCULINO-QUEVEDO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (48, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (49, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (50, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-LOJA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (51, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-PORTOVIEJO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (52, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-PUYO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (53, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-RIOBAMBA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (54, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-SANTO DOMINGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (55, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL MIXTO-SUCUMBIOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (56, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL RSCN MIXTO-COTOPAXI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (57, 'CENTRO DE PRIVACIÓN PROVISIONAL DE LIBERTAD (CPPL)', 'CPPL RSCS MASCULINO-TURI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (58, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CPPL MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (59, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS FEMENINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (60, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS FEMENINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (61, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS FEMENINO-PORTOVIEJO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (62, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS FEMENINO-QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (63, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS FEMENINO-ZARUMA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (64, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-AZOGUES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (65, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-BAHIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (66, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-CAÑAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (67, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-EL REDEO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (68, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (69, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (70, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-IBARRA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (71, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-JIPIJAPA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (72, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-MACHALA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (73, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MASCULINO-SUCUMBIOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (74, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (75, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-ARCHIDONA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (76, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-GUARANDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (77, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-LOJA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (78, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-MACAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (79, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-QUEVEDO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (80, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-RIOBAMBA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (81, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-SANTO DOMINGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (82, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS MIXTO-TULCAN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (83, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS RSCN MIXTO-COTOPAXI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (84, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS RSCS MIXTO-TURI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (85, 'CENTRO DE REHABILITACIÓN SOCIAL (CRS)', 'CRS RZ8 MASCULINO-GUAYAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (86, 'CENTROS DE DIVERSIÓN', 'BAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (87, 'CENTROS DE DIVERSIÓN', 'BILLAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (88, 'CENTROS DE DIVERSIÓN', 'CASA DE CITAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (89, 'CENTROS DE DIVERSIÓN', 'DISCOTECA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (90, 'CENTROS DE DIVERSIÓN', 'GALLERAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (91, 'CENTROS DE DIVERSIÓN', 'KARAOQUE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (92, 'CENTROS DE DIVERSIÓN', 'LICORERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (93, 'CENTROS DE DIVERSIÓN', 'NIGHT CLUB');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (94, 'CENTROS DE DIVERSIÓN', 'OTRO CENTRO DE DIVERSIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (95, 'CENTROS DE DIVERSIÓN', 'SALA DE JUEGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (96, 'ENTIDADES FINANCIERAS', 'BANCO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (97, 'ENTIDADES FINANCIERAS', 'CAJERO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (98, 'ENTIDADES FINANCIERAS', 'COOPERATIVA DE AHORRO Y CRÉDITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (99, 'ENTIDADES FINANCIERAS', 'SOCIEDAD FINANCIERA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (100, 'ENTIDADES FINANCIERAS', 'UNIDADES DE SERVICIOS FINANCIEROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (101, 'ENTIDADES PUBLICAS', 'AGENCIA DE REGULACIÓN Y CONTROL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (102, 'ENTIDADES PUBLICAS', 'CENTRO DE DETENCIÓN PROVISIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (103, 'ENTIDADES PUBLICAS', 'CENTRO DE REHABILITACIÓN SOCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (104, 'ENTIDADES PUBLICAS', 'CENTROS DE REHABILITACIÓN SOCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (105, 'ENTIDADES PUBLICAS', 'COMANDANCIA GENERAL DE POLICÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (106, 'ENTIDADES PUBLICAS', 'CONSEJO DE LA JUDICATURA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (107, 'ENTIDADES PUBLICAS', 'CONSEJOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (108, 'ENTIDADES PUBLICAS', 'CORTE CONSTITUCIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (109, 'ENTIDADES PUBLICAS', 'CORTE NACIONAL DE JUSTICIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (110, 'ENTIDADES PUBLICAS', 'DEFENSORÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (111, 'ENTIDADES PUBLICAS', 'DIRECCIONES NACIONALES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (112, 'ENTIDADES PUBLICAS', 'EMPRESAS PUBLICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (113, 'ENTIDADES PUBLICAS', 'ESTACIÓN DE BOMBEROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (114, 'ENTIDADES PUBLICAS', 'FISCALÍA GENERAL DEL ESTADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (115, 'ENTIDADES PUBLICAS', 'FUERZA DE SEGURIDAD PÚBLICA Y DEL ESTADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (116, 'ENTIDADES PUBLICAS', 'GOBIERNOS AUTÓNOMOS DESCENTRALIZADOS (GADS)');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (117, 'ENTIDADES PUBLICAS', 'INSTITUTOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (118, 'ENTIDADES PUBLICAS', 'JUZGADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (119, 'ENTIDADES PUBLICAS', 'MINISTERIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (120, 'ENTIDADES PUBLICAS', 'REGISTRO CIVIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (121, 'ENTIDADES PUBLICAS', 'SECRETARIAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (122, 'ENTIDADES PUBLICAS', 'SERVICIOS PÚBLICOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (123, 'INSTITUCIONES DE SALUD', 'CENTRO Y SUBCENTRO DE SALUD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (124, 'INSTITUCIONES DE SALUD', 'CLÍNICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (125, 'INSTITUCIONES DE SALUD', 'DISPENSARIO MÉDICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (126, 'INSTITUCIONES DE SALUD', 'FARMACIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (127, 'INSTITUCIONES DE SALUD', 'HOSPITAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (128, 'INSTITUCIONES DE SALUD', 'LABORATORIO CLÍNICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (129, 'INSTITUCIONES DE SALUD', 'PUESTO DE SALUD (CONSULTORIOS MÉDICOS)');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (130, 'INSTITUCIONES EDUCATIVAS', 'CENTRO DE CAPACITACIÓN Y FORMACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (131, 'INSTITUCIONES EDUCATIVAS', 'CENTRO INFANTILE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (132, 'INSTITUCIONES EDUCATIVAS', 'COLEGIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (133, 'INSTITUCIONES EDUCATIVAS', 'ESCUELA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (134, 'INSTITUCIONES EDUCATIVAS', 'INSTITUTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (135, 'INSTITUCIONES EDUCATIVAS', 'UNIDAD EDUCATIVA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (136, 'INSTITUCIONES EDUCATIVAS', 'UNIVERSIDAD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (137, 'LUGARES QUE PRESTAN SERVICIOS', 'AGENCIA DE VIAJE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (138, 'LUGARES QUE PRESTAN SERVICIOS', 'BALNEARIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (139, 'LUGARES QUE PRESTAN SERVICIOS', 'BODEGA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (140, 'LUGARES QUE PRESTAN SERVICIOS', 'CABINA-CENTRO DE INTERNET');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (141, 'LUGARES QUE PRESTAN SERVICIOS', 'CAFETERÍAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (142, 'LUGARES QUE PRESTAN SERVICIOS', 'COMPAÑÍA TELEFÓNICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (143, 'LUGARES QUE PRESTAN SERVICIOS', 'FUNDACION-ASOCIACIÓN Y ORGANIZACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (144, 'LUGARES QUE PRESTAN SERVICIOS', 'GASOLINERA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (145, 'LUGARES QUE PRESTAN SERVICIOS', 'GIMNASIO O SPA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (146, 'LUGARES QUE PRESTAN SERVICIOS', 'HELADERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (147, 'LUGARES QUE PRESTAN SERVICIOS', 'INDUSTRIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (148, 'LUGARES QUE PRESTAN SERVICIOS', 'LOCAL DE EVENTOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (149, 'LUGARES QUE PRESTAN SERVICIOS', 'LOCAL DE NECESIDADES BÁSICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (150, 'LUGARES QUE PRESTAN SERVICIOS', 'MECÁNICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (151, 'LUGARES QUE PRESTAN SERVICIOS', 'MEDIO DE COMUNICACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (152, 'LUGARES QUE PRESTAN SERVICIOS', 'PANADERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (153, 'LUGARES QUE PRESTAN SERVICIOS', 'PARQUEADERO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (154, 'LUGARES QUE PRESTAN SERVICIOS', 'PATIO DE COMIDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (155, 'LUGARES QUE PRESTAN SERVICIOS', 'RESTAURANTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (156, 'LUGARES QUE PRESTAN SERVICIOS', 'SALA DE BELLEZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (157, 'LUGARES QUE PRESTAN SERVICIOS', 'VULCANIZADORA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (158, 'SIN DATO', '"\\"CPPL MASCULINO-CC GUAYAQUIL \\"\\"APREMIO\\"\\"\\""');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (159, 'SIN DATO', 'AEROPUERTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (160, 'SIN DATO', 'AGENCIA DE CORREOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (161, 'SIN DATO', 'AGENCIA DE REGULACIÓN Y CONTROL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (162, 'SIN DATO', 'AGENCIA DE VIAJE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (163, 'SIN DATO', 'AGENCIA NACIONAL DE TRÁNSITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (164, 'SIN DATO', 'ALMACEN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (165, 'SIN DATO', 'ALTAMAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (166, 'SIN DATO', 'BALNEARIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (167, 'SIN DATO', 'BANCO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (168, 'SIN DATO', 'BAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (169, 'SIN DATO', 'BAZAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (170, 'SIN DATO', 'BILLAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (171, 'SIN DATO', 'BODEGA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (172, 'SIN DATO', 'BOSQUES Y RESERVAS ECOLÓGICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (173, 'SIN DATO', 'CABINA-CENTRO DE INTERNET');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (174, 'SIN DATO', 'CAFETERÍAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (175, 'SIN DATO', 'CAI MASCULINO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (176, 'SIN DATO', 'CAI MASCULINO-CUENCA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (177, 'SIN DATO', 'CAI MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (178, 'SIN DATO', 'CAI MASCULINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (179, 'SIN DATO', 'CAI MASCULINO-IBARRA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (180, 'SIN DATO', 'CAI MASCULINO-QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (181, 'SIN DATO', 'CAJERO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (182, 'SIN DATO', 'CANCHAS DE USO MÚLTIPLE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (183, 'SIN DATO', 'CASA DE CAMBIO - EMPEÑO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (184, 'SIN DATO', 'CASA DE PROTECCIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (185, 'SIN DATO', 'CASA DE SEGURIDAD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (186, 'SIN DATO', 'CASA/VILLA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (187, 'SIN DATO', 'CEMENTERIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (188, 'SIN DATO', 'CENTRO COMERCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (189, 'SIN DATO', 'CENTRO DE ADOLESCENTES INFRACTORES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (190, 'SIN DATO', 'CENTRO DE CAPACITACIÓN Y FORMACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (191, 'SIN DATO', 'CENTRO DE DETENCIÓN PROVISIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (192, 'SIN DATO', 'CENTRO DE REHABILITACIÓN SOCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (193, 'SIN DATO', 'CENTRO INFANTILE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (194, 'SIN DATO', 'CENTRO Y SUBCENTRO DE SALUD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (195, 'SIN DATO', 'CENTROS DE REHABILITACIÓN SOCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (196, 'SIN DATO', 'CLÍNICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (197, 'SIN DATO', 'COLEGIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (198, 'SIN DATO', 'COLISEO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (199, 'SIN DATO', 'COMANDANCIA GENERAL DE POLICÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (200, 'SIN DATO', 'COMISIÓN DE TRÁNSITO DEL ECUADOR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (201, 'SIN DATO', 'CONJUNTO HABITACIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (202, 'SIN DATO', 'CONSEJO DE LA JUDICATURA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (203, 'SIN DATO', 'CONSEJOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (204, 'SIN DATO', 'CONTRALORÍA GENERAL DEL ESTADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (205, 'SIN DATO', 'CONTROLES FIJOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (206, 'SIN DATO', 'COOPERATIVA DE AHORRO Y CRÉDITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (207, 'SIN DATO', 'COOPERATIVA DE TRASPORTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (208, 'SIN DATO', 'CORTE CONSTITUCIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (209, 'SIN DATO', 'CORTE NACIONAL DE JUSTICIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (210, 'SIN DATO', 'COVACHA/CHOZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (211, 'SIN DATO', 'CPPL MASCULINO-AZOGUES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (212, 'SIN DATO', 'CPPL MASCULINO-BABAHOYO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (213, 'SIN DATO', 'CPPL MASCULINO-BAHIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (214, 'SIN DATO', 'CPPL MASCULINO-EL INCA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (215, 'SIN DATO', 'CPPL MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (216, 'SIN DATO', 'CPPL MASCULINO-GUARANDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (217, 'SIN DATO', 'CPPL MASCULINO-MACAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (218, 'SIN DATO', 'CPPL MASCULINO-QUEVEDO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (219, 'SIN DATO', 'CPPL MIXTO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (220, 'SIN DATO', 'CPPL MIXTO-ARCHIDONA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (221, 'SIN DATO', 'CPPL MIXTO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (222, 'SIN DATO', 'CPPL MIXTO-LOJA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (223, 'SIN DATO', 'CPPL MIXTO-PORTOVIEJO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (224, 'SIN DATO', 'CPPL MIXTO-PUYO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (225, 'SIN DATO', 'CPPL MIXTO-RIOBAMBA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (226, 'SIN DATO', 'CPPL MIXTO-SANTO DOMINGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (227, 'SIN DATO', 'CPPL MIXTO-SUCUMBIOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (228, 'SIN DATO', 'CPPL RSCN MIXTO-COTOPAXI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (229, 'SIN DATO', 'CPPL RSCS MASCULINO-TURI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (230, 'SIN DATO', 'CRS FEMENINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (231, 'SIN DATO', 'CRS FEMENINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (232, 'SIN DATO', 'CRS FEMENINO-PORTOVIEJO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (233, 'SIN DATO', 'CRS FEMENINO-QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (234, 'SIN DATO', 'CRS FEMENINO-ZARUMA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (235, 'SIN DATO', 'CRS MASCULINO-AZOGUES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (236, 'SIN DATO', 'CRS MASCULINO-BABAHOYO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (237, 'SIN DATO', 'CRS MASCULINO-BAHIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (238, 'SIN DATO', 'CRS MASCULINO-CAÑAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (239, 'SIN DATO', 'CRS MASCULINO-EL CONDADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (240, 'SIN DATO', 'CRS MASCULINO-EL REDEO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (241, 'SIN DATO', 'CRS MASCULINO-ESMERALDAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (242, 'SIN DATO', 'CRS MASCULINO-GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (243, 'SIN DATO', 'CRS MASCULINO-IBARRA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (244, 'SIN DATO', 'CRS MASCULINO-JIPIJAPA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (245, 'SIN DATO', 'CRS MASCULINO-MACHALA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (246, 'SIN DATO', 'CRS MASCULINO-SUCUMBIOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (247, 'SIN DATO', 'CRS MIXTO-AMBATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (248, 'SIN DATO', 'CRS MIXTO-ARCHIDONA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (249, 'SIN DATO', 'CRS MIXTO-GUARANDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (250, 'SIN DATO', 'CRS MIXTO-LOJA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (251, 'SIN DATO', 'CRS MIXTO-MACAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (252, 'SIN DATO', 'CRS MIXTO-QUEVEDO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (253, 'SIN DATO', 'CRS MIXTO-RIOBAMBA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (254, 'SIN DATO', 'CRS MIXTO-SANTO DOMINGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (255, 'SIN DATO', 'CRS MIXTO-TULCAN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (256, 'SIN DATO', 'CRS RSCN MIXTO-COTOPAXI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (257, 'SIN DATO', 'CRS RSCS MIXTO-TURI');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (258, 'SIN DATO', 'CRS RZ8 MASCULINO-GUAYAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (259, 'SIN DATO', 'CUARTO EN CASA DE INQUILINATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (260, 'SIN DATO', 'DEFENSORÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (261, 'SIN DATO', 'DEPARTAMENTO EN CASA O EDIFICIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (262, 'SIN DATO', 'DIRECCIONES NACIONALES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (263, 'SIN DATO', 'DISCOTECA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (264, 'SIN DATO', 'DISPENSARIO MÉDICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (265, 'SIN DATO', 'EMPRESAS PUBLICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (266, 'SIN DATO', 'ESCUELA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (267, 'SIN DATO', 'ESPACIO PRIVADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (268, 'SIN DATO', 'ESTACIÓN DE BOMBEROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (269, 'SIN DATO', 'ESTADIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (270, 'SIN DATO', 'FARMACIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (271, 'SIN DATO', 'FERIA DE VEHÍCULO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (272, 'SIN DATO', 'FERIA LIBRE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (273, 'SIN DATO', 'FERRETERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (274, 'SIN DATO', 'FINCA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (275, 'SIN DATO', 'FISCALÍA GENERAL DEL ESTADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (276, 'SIN DATO', 'FUERZA DE SEGURIDAD PÚBLICA Y DEL ESTADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (277, 'SIN DATO', 'FUERZAS ARMADAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (278, 'SIN DATO', 'FUNDACION-ASOCIACIÓN Y ORGANIZACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (279, 'SIN DATO', 'GALLERAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (280, 'SIN DATO', 'GASOLINERA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (281, 'SIN DATO', 'GIMNASIO O SPA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (282, 'SIN DATO', 'GOBIERNOS AUTÓNOMOS DESCENTRALIZADOS (GADS)');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (283, 'SIN DATO', 'HACIENDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (284, 'SIN DATO', 'HELADERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (285, 'SIN DATO', 'HOGAR DE JUBILACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (286, 'SIN DATO', 'HOSPITAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (287, 'SIN DATO', 'HOSTAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (288, 'SIN DATO', 'HOTEL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (289, 'SIN DATO', 'IGLESIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (290, 'SIN DATO', 'INDUSTRIA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (291, 'SIN DATO', 'INSTALACION DE ATENCIÓN INSTITUCIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (292, 'SIN DATO', 'INSTITUTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (293, 'SIN DATO', 'INSTITUTOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (294, 'SIN DATO', 'JUZGADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (295, 'SIN DATO', 'KARAOQUE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (296, 'SIN DATO', 'LABORATORIO CLÍNICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (297, 'SIN DATO', 'LAGUNA-LAGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (298, 'SIN DATO', 'LICORERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (299, 'SIN DATO', 'LOCAL DE EVENTOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (300, 'SIN DATO', 'LOCAL DE NECESIDADES BÁSICAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (301, 'SIN DATO', 'LUGAR AEROPUERTO TÚNEL DE EQUIPAJES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (302, 'SIN DATO', 'MAR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (303, 'SIN DATO', 'MECÁNICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (304, 'SIN DATO', 'MEDIAGUA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (305, 'SIN DATO', 'MEDIO DE COMUNICACIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (306, 'SIN DATO', 'MERCADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (307, 'SIN DATO', 'MINISTERIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (308, 'SIN DATO', 'MOTEL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (309, 'SIN DATO', 'MUELLE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (310, 'SIN DATO', 'NIGHT CLUB');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (311, 'SIN DATO', 'OTRO CENTRO DE DIVERSIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (312, 'SIN DATO', 'OTRO LOCAL COMERCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (313, 'SIN DATO', 'OTRO LUGAR DE INSPECIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (314, 'SIN DATO', 'PANADERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (315, 'SIN DATO', 'PAPELERÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (316, 'SIN DATO', 'PARADA DE BUSES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (317, 'SIN DATO', 'PARQUE Y PLAZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (318, 'SIN DATO', 'PARQUEADERO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (319, 'SIN DATO', 'PATIO DE COMIDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (320, 'SIN DATO', 'PLAYA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (321, 'SIN DATO', 'PLAZA DE TOROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (322, 'SIN DATO', 'POLICÍA NACIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (323, 'SIN DATO', 'PUERTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (324, 'SIN DATO', 'PUERTO MARÍTIMO BAHÍA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (325, 'SIN DATO', 'PUERTO MARÍTIMO EMBARCACIONES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (326, 'SIN DATO', 'PUERTO MARÍTIMO PATÍOS DE INSPECCIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (327, 'SIN DATO', 'PUESTO DE SALUD (CONSULTORIOS MÉDICOS)');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (328, 'SIN DATO', 'QUEBRADA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (329, 'SIN DATO', 'QUINTA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (330, 'SIN DATO', 'RANCHO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (331, 'SIN DATO', 'REGISTRO CIVIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (332, 'SIN DATO', 'RESIDENCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (333, 'SIN DATO', 'RESTAURANTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (334, 'SIN DATO', 'RÍO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (335, 'SIN DATO', 'SALA DE BELLEZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (336, 'SIN DATO', 'SALA DE JUEGO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (337, 'SIN DATO', 'SECRETARIAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (338, 'SIN DATO', 'SEMÁFORO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (339, 'SIN DATO', 'SERVICIOS PÚBLICOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (340, 'SIN DATO', 'SIN DATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (341, 'SIN DATO', 'SIS ECU-911');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (342, 'SIN DATO', 'TERMINAL TERRESTRE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (343, 'SIN DATO', 'TERRENO BALDÍO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (344, 'SIN DATO', 'TIENDA-MICRO MERCADO-ABARROTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (345, 'SIN DATO', 'TRANSPORTE PRIVADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (346, 'SIN DATO', 'TRANSPORTE PÚBLICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (347, 'SIN DATO', 'TRIBUNAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (348, 'SIN DATO', 'TROCHA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (349, 'SIN DATO', 'UNIDAD DE ASEGURAMIENTO TRANSITORIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (350, 'SIN DATO', 'UNIDAD DE FLAGRANCIA GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (351, 'SIN DATO', 'UNIDAD DE FLAGRANCIA QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (352, 'SIN DATO', 'UNIDAD EDUCATIVA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (353, 'SIN DATO', 'UNIDAD JUDICIAL NORTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (354, 'SIN DATO', 'UNIDAD JUDICIAL QUITUMBE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (355, 'SIN DATO', 'UNIDADES DE SERVICIOS FINANCIEROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (356, 'SIN DATO', 'UNIVERSIDAD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (357, 'SIN DATO', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (358, 'SIN DATO', 'VULCANIZADORA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (359, 'TRANSPORTE', 'AEROPUERTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (360, 'TRANSPORTE', 'COOPERATIVA DE TRASPORTE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (361, 'TRANSPORTE', 'METRO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (362, 'TRANSPORTE', 'PUERTO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (363, 'TRANSPORTE', 'TERMINAL TERRESTRE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (364, 'TRANSPORTE', 'TRANSPORTE PRIVADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (365, 'TRANSPORTE', 'TRANSPORTE PÚBLICO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (366, 'TRANSPORTE', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (367, 'UNIDADES DE ASEGURAMIENTO TRANSITORIO (UAT)', 'UNIDAD DE ASEGURAMIENTO TRANSITORIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (368, 'UNIDADES DE ASEGURAMIENTO TRANSITORIO (UAT)', 'UNIDAD DE FLAGRANCIA GUAYAQUIL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (369, 'UNIDADES DE ASEGURAMIENTO TRANSITORIO (UAT)', 'UNIDAD DE FLAGRANCIA MANTA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (370, 'UNIDADES DE ASEGURAMIENTO TRANSITORIO (UAT)', 'UNIDAD DE FLAGRANCIA QUITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (371, 'UNIDADES DE ASEGURAMIENTO TRANSITORIO (UAT)', 'UNIDAD JUDICIAL QUITUMBE');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (372, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'AGENCIA NACIONAL DE TRÁNSITO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (373, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'COMISIÓN DE TRÁNSITO DEL ECUADOR');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (374, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'CUERPOS DE BOMBEROS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (375, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'FUERZAS ARMADAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (376, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'POLICÍA NACIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (377, 'UNIDADES DE REACCIÓN Y EMERGENCIA', 'SIS ECU-911');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (378, 'VIVIENDA/ALOJAMIENTO', 'CASA DE PROTECCIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (379, 'VIVIENDA/ALOJAMIENTO', 'CASA DE SEGURIDAD');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (380, 'VIVIENDA/ALOJAMIENTO', 'CASA/VILLA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (381, 'VIVIENDA/ALOJAMIENTO', 'CONJUNTO HABITACIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (382, 'VIVIENDA/ALOJAMIENTO', 'COVACHA/CHOZA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (383, 'VIVIENDA/ALOJAMIENTO', 'CUARTO EN CASA DE INQUILINATO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (384, 'VIVIENDA/ALOJAMIENTO', 'DEPARTAMENTO EN CASA O EDIFICIO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (385, 'VIVIENDA/ALOJAMIENTO', 'ESPACIO PRIVADO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (386, 'VIVIENDA/ALOJAMIENTO', 'FINCA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (387, 'VIVIENDA/ALOJAMIENTO', 'HACIENDA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (388, 'VIVIENDA/ALOJAMIENTO', 'HOGAR DE ATENCIÓN RESIDENCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (389, 'VIVIENDA/ALOJAMIENTO', 'HOSTAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (390, 'VIVIENDA/ALOJAMIENTO', 'HOTEL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (391, 'VIVIENDA/ALOJAMIENTO', 'INSTALACION DE ATENCIÓN INSTITUCIONAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (392, 'VIVIENDA/ALOJAMIENTO', 'MEDIAGUA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (393, 'VIVIENDA/ALOJAMIENTO', 'MOTEL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (394, 'VIVIENDA/ALOJAMIENTO', 'QUINTA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (395, 'VIVIENDA/ALOJAMIENTO', 'RANCHO');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (396, 'VIVIENDA/ALOJAMIENTO', 'RESIDENCIAL');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (397, 'VIVIENDA/ALOJAMIENTO', 'VÍA PÚBLICA');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (398, 'ZONA DE INSPECCIÓN', 'AEROPUERTO CARGUERAS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (399, 'ZONA DE INSPECCIÓN', 'AEROPUERTO CURIER');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (400, 'ZONA DE INSPECCIÓN', 'CONTROLES FIJOS');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (401, 'ZONA DE INSPECCIÓN', 'LUGAR AEROPUERTO TÚNEL DE EQUIPAJES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (402, 'ZONA DE INSPECCIÓN', 'OTRO LUGAR DE INSPECIÓN');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (403, 'ZONA DE INSPECCIÓN', 'PUERTO MARÍTIMO EMBARCACIONES');
INSERT INTO utpl.lugar (codigo, tipo, nombre) VALUES (404, 'ZONA DE INSPECCIÓN', 'PUERTO MARÍTIMO PATÍOS DE INSPECCIÓN');
