INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (1, 'AZUAY', 6);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (2, 'BOLIVAR', 5);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (3, 'CAÑAR', 6);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (4, 'CARCHI', 1);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (5, 'COTOPAXI', 3);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (6, 'CHIMBORAZO', 3);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (7, 'EL ORO', 7);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (8, 'ESMERALDAS', 1);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (9, 'GUAYAS', 5);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (10, 'IMBABURA', 1);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (11, 'LOJA', 7);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (12, 'LOS RIOS', 5);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (13, 'MANABI', 4);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (14, 'MORONA SANTIAGO', 6);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (15, 'NAPO', 2);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (16, 'PASTAZA', 3);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (17, 'PICHINCHA', 2);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (18, 'TUNGURAHUA', 3);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (19, 'ZAMORA CHINCHIPE', 7);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (20, 'GALAPAGOS', 5);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (21, 'SUCUMBIOS', 1);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (22, 'ORELLANA', 2);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (23, 'SANTO DOMINGO DE LOS TSACHILAS', 4);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (24, 'SANTA ELENA', 5);
INSERT INTO utpl.provincia (codigo, nombre, zona_codigo) VALUES (88, 'MAR TERRITORIAL', 10);
