DROP SCHEMA IF EXISTS movie_4_practice;
CREATE SCHEMA movie_4_practice;
USE movie_4_practice;


CREATE TABLE ACTOR
(
ID INT AUTO_INCREMENT,
NAME VARCHAR(512) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE GENRE
(
ID INT AUTO_INCREMENT,
NAME VARCHAR(512) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE MOVIE
(
ID INT AUTO_INCREMENT,
NAME VARCHAR(1024) NOT NULL,
RATING DECIMAL(4,2) DEFAULT 0,
VOTES INT DEFAULT 0,
META_SCORE INT DEFAULT 0,
PG_RATING VARCHAR(10) DEFAULT 'NA',
YEAR INT(4) NOT NULL,
DURATION INT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE MOVIE_ACTOR
(
MOVIE_ID INT,
ACTOR_ID INT,
PRIMARY KEY (MOVIE_ID,ACTOR_ID)
);

CREATE TABLE MOVIE_GENRE
(
ID_MOVIE INT,
ID_GENRE INT
);

ALTER TABLE MOVIE_ACTOR ADD FOREIGN KEY MOVIE_ID_idxfk (MOVIE_ID) REFERENCES MOVIE (ID);

ALTER TABLE MOVIE_ACTOR ADD FOREIGN KEY ACTOR_ID_idxfk (ACTOR_ID) REFERENCES ACTOR (ID);

ALTER TABLE MOVIE_GENRE ADD FOREIGN KEY ID_MOVIE_idxfk (ID_MOVIE) REFERENCES MOVIE (ID);

ALTER TABLE MOVIE_GENRE ADD FOREIGN KEY ID_GENRE_idxfk (ID_GENRE) REFERENCES GENRE (ID);
